env:
  es2021: true
  node: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - jest
rules:
  import/extensions: 
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]

  # My rules:
  no-console: 0
  # camelcase: off
  # consistent-return: 0
  # prefer-template: 0
  # import/no-extraneous-dependencies: 0
